# Generated by Django 4.2.16 on 2024-11-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='edad',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='fecha_union',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='correo_electronico',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='esta_activo',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='es_personal',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='es_superusuario',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nombre_de_usuario',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='default_username', max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
